import { Inter } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import ThemeProviders from '@/Theme/ThemeProvider';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
           <ThemeProviders>
           {children}
           </ThemeProviders>

          </AppRouterCacheProvider>
       
        </body>
    </html>
  )
}
